/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import modelo.*;
import TDA.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author n04605
 */
public class ListaDependencias extends javax.swing.JFrame {

    private Lista RDependencias;
    private DefaultTableModel modeloTabla;
    
    public ListaDependencias() {
        initComponents();
    }
    
    public ListaDependencias(Lista RDependencias) {
        initComponents();
        this.RDependencias=RDependencias;
        modeloTabla = new DefaultTableModel();
        this.TablaDependencias.setModel(modeloTabla);
        // Crear las columnas de la Tabla
        modeloTabla.addColumn("N°");
        modeloTabla.addColumn("Nombre");
        CargarTabla();
    }

    private void CargarTabla() {
        int filas=this.TablaDependencias.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        Lista<Dependencia> listaDependencia = this.RDependencias.obtenerListaDependencias();
        Nodo<Dependencia> aux = listaDependencia.getCabeza();
        int num=1;
        while (aux != null) {
            Dependencia ObjDependencia = aux.getElemento();
            String[] fila = new String[2];
            fila[0] = String.valueOf(num);
            fila[1] = ObjDependencia.getNombre();
            modeloTabla.addRow(fila);
            aux = aux.getSgteNodo();
            num++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDependencias = new javax.swing.JTable();
        RegistroExpediente = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Dependencias");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DEPENDENCIAS");

        TablaDependencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "N°", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDependencias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaDependencias);
        if (TablaDependencias.getColumnModel().getColumnCount() > 0) {
            TablaDependencias.getColumnModel().getColumn(0).setResizable(false);
            TablaDependencias.getColumnModel().getColumn(1).setResizable(false);
        }

        RegistroExpediente.setText("Registrar");
        RegistroExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroExpedienteActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistroExpediente)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar)
                        .addGap(75, 75, 75)
                        .addComponent(jButton4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroExpediente)
                    .addComponent(Eliminar)
                    .addComponent(jButton4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void RegistroExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroExpedienteActionPerformed
        String nombre=JOptionPane.showInputDialog(null, "Ingrese el nombre de la Dependencia:");
        if (nombre.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "¡No asignó un nombre!");
        }
        else {
            Dependencia oDependencia = new Dependencia(nombre);
            this.RDependencias.agregar(oDependencia);
            CargarTabla();
        }
    }//GEN-LAST:event_RegistroExpedienteActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int fila=-1;
        fila = TablaDependencias.getSelectedRow();
        if (fila!=-1) {
            String aBuscar= TablaDependencias.getValueAt(fila,1).toString();
            this.RDependencias.eliminarPorNombre(aBuscar);
            CargarTabla();
        }
        else{
            JOptionPane.showMessageDialog(null,"¡Seleccione una fila!");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDependencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton RegistroExpediente;
    private javax.swing.JTable TablaDependencias;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
