/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import modelo.*;
import TDA.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class RegistroPersona extends javax.swing.JFrame {
    private Lista Registro;
    private DefaultTableModel modeloTabla;
    
    public RegistroPersona() {
        initComponents();
        this.Registro = new Lista<>();
    }

    public RegistroPersona(Lista Registro) {
        initComponents();
        this.Registro = Registro;
    }
    
    public RegistroPersona(Lista Registro, DefaultTableModel modeloTabla) {
        initComponents();
        this.Registro = Registro;
        this.modeloTabla=modeloTabla;
    }
    
    public RegistroPersona(Lista Registro, DefaultTableModel modeloTabla, String tipo) {
        initComponents();
        this.Registro = Registro;
        this.modeloTabla=modeloTabla;
        this.Tipo.setText(tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNombres = new javax.swing.JTextField();
        tDNI = new javax.swing.JTextField();
        tCorreo = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        BGrabar = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de persona");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO");

        jLabel3.setText("Nombres:");

        jLabel4.setText("DNI:");

        jLabel5.setText("Correo electrónico:");

        jLabel6.setText("Teléfono:");

        tNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombresActionPerformed(evt);
            }
        });

        tDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDNIActionPerformed(evt);
            }
        });

        BGrabar.setText("Grabar");
        BGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrabarActionPerformed(evt);
            }
        });

        BCerrar.setText("Cerrar");
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo:");

        Tipo.setEditable(false);
        Tipo.setFocusable(false);
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(350, Short.MAX_VALUE)
                        .addComponent(BCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BGrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tCorreo)
                                    .addComponent(tNombres)
                                    .addComponent(tDNI, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(BGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCerrar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrabarActionPerformed
        String nombre = this.tNombres.getText();
        String DNI = this.tDNI.getText();
        String correo = this.tCorreo.getText();
        String telefono=this.tTelefono.getText();
        String txt = String.valueOf(this.Tipo.getText());
        if (nombre.equalsIgnoreCase("") || DNI.equalsIgnoreCase("") || correo.equalsIgnoreCase("") || telefono.equalsIgnoreCase("") || txt.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "¡Falta completar datos!");
        }
        else {
            if ("Interno".equals(txt)) {
                Interno oInterno = new Interno(DNI, nombre, telefono, correo);
                this.Registro.agregar(oInterno);
                JOptionPane.showMessageDialog(null, "¡Se registró exitosamente!");
            } 
            else if ("Externo".equals(txt)) {
                Externo oExterno = new Externo(DNI, nombre, telefono, correo);
                this.Registro.agregar(oExterno);
                JOptionPane.showMessageDialog(null, "¡Se registró exitosamente!");
            }
            this.tTelefono.setText(null);
            this.tDNI.setText(null);
            this.tCorreo.setText(null);
            this.tNombres.setText(null);
            CargarTabla();
        }
    }//GEN-LAST:event_BGrabarActionPerformed

    private void CargarTabla() {
        int filas=modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        
        String txt = String.valueOf(this.Tipo.getText());
        if ("Interno".equals(txt)) {
            Lista<Interno> listaInternos = this.Registro.obtenerListaInternos();
            Nodo<Interno> aux = listaInternos.getCabeza();
            while (aux != null) {
                Interno ObjInterno = aux.getElemento();
                String[] fila = new String[4];
                fila[0] = ObjInterno.getNombres();
                fila[1] = ObjInterno.getDni();
                fila[2] = ObjInterno.getEmail();
                fila[3] = ObjInterno.getTelefono();
                modeloTabla.addRow(fila);
                aux = aux.getSgteNodo();
            }
            ListaEmpleados listaEmp = new ListaEmpleados();
            listaEmp.setModeloTabla(modeloTabla);
        }
        else if ("Externo".equals(txt)) {
            Lista<Externo> listaExternos = this.Registro.obtenerListaExternos();
            Nodo<Externo> aux = listaExternos.getCabeza();
            while (aux != null) {
                Externo ObjExterno = aux.getElemento();
                String[] fila = new String[4];
                fila[0] = ObjExterno.getNombres();
                fila[1] = ObjExterno.getDni();
                fila[2] = ObjExterno.getEmail();
                fila[3] = ObjExterno.getTelefono();
                modeloTabla.addRow(fila);
                aux = aux.getSgteNodo();
            }
            ListaUsuarios listaU = new ListaUsuarios();
            listaU.setModeloTabla(modeloTabla);
        }
    }
    
    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BCerrarActionPerformed

    private void tDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDNIActionPerformed

    private void tNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombresActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BGrabar;
    private javax.swing.JTextField Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tNombres;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
