/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import TDA.*;
import modelo.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class RegistroExpediente extends javax.swing.JFrame {
    private Cola RExpedientes;
    private Lista Registro;
    private Lista RDependencias;
    private DefaultComboBoxModel modeloComboUsuario;
    private DefaultComboBoxModel modeloComboDependencia;
    
    public RegistroExpediente() {
        initComponents();
        this.Registro = new Lista<>();
        this.RDependencias = new Lista<>();
        this.RExpedientes = new Cola<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String horaActual = dateFormat.format(new Date());
        tFyH.setText(horaActual);
        tFyH.setEditable(false);
        
    }

    public RegistroExpediente(Cola Rexpedientes,Lista Registro, Lista RDependencias) {
        initComponents();
        this.RExpedientes = Rexpedientes;
        this.Registro = Registro;
        this.RDependencias = RDependencias;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String horaActual = dateFormat.format(new Date());
        tFyH.setText(horaActual);
        tFyH.setEditable(false);
        modeloComboUsuario = new DefaultComboBoxModel();
        modeloComboDependencia = new DefaultComboBoxModel();
        this.cUsuario.setModel(modeloComboUsuario);
        this.cDependencia.setModel(modeloComboDependencia);
        llenarUsuarios();
        llenarDependencias();
    }
    
    private void llenarUsuarios() {
        Lista<Usuario> listaUsuarios = this.Registro.obtenerListaUsuarios();
        Nodo<Usuario> aux = listaUsuarios.getCabeza();
        while (aux != null) {
            Usuario ObjUsuario = aux.getElemento();
            this.modeloComboUsuario.addElement(ObjUsuario);
            aux = aux.getSgteNodo();
        }
    }
    
    private void llenarDependencias() {
        Lista<Dependencia> listaDependencias = this.RDependencias.obtenerListaDependencias();
        Nodo<Dependencia> aux = listaDependencias.getCabeza();
        while (aux != null) {
            Dependencia ObjDependencia = aux.getElemento();
            this.modeloComboDependencia.addElement(ObjDependencia);
            aux = aux.getSgteNodo();
        }
    }
    
    public boolean esEntero(String cadena) {
        if (cadena == null || cadena.isEmpty()) {
            return false;
        }

        for (int i = 0; i < cadena.length(); i++) {
            char caracter = cadena.charAt(i);
            if (i == 0 && (caracter == '+' || caracter == '-')) {
                continue;
            }
            if (!Character.isDigit(caracter)) {
                return false;
            }
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        tPrioridad = new javax.swing.JTextField();
        tAsunto = new javax.swing.JTextField();
        tDocs = new javax.swing.JTextField();
        tFyH = new javax.swing.JTextField();
        BGrabar = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cUsuario = new javax.swing.JComboBox<>();
        cDependencia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de expediente");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE EXPEDIENTE");

        jLabel2.setText("ID único:");

        jLabel3.setText("Número de prioridad:");

        jLabel8.setText("Asunto:");

        jLabel9.setText("Documentos de referencia:");

        jLabel10.setText("Fecha y hora de inicio:");

        tID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDActionPerformed(evt);
            }
        });

        tFyH.setFocusable(false);

        BGrabar.setText("Grabar");
        BGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrabarActionPerformed(evt);
            }
        });

        BCerrar.setText("Cerrar");
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Usuario:");

        jLabel12.setText("Dependencia:");

        cUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });

        cDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tPrioridad)
                                    .addComponent(tID)
                                    .addComponent(tAsunto)
                                    .addComponent(tDocs)
                                    .addComponent(tFyH)
                                    .addComponent(cUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cDependencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 149, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCerrar)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDocs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFyH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(BGrabar)
                .addGap(28, 28, 28)
                .addComponent(BCerrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIDActionPerformed

    private void BGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrabarActionPerformed
        String id = this.tID.getText();
        String prio = this.tPrioridad.getText();
        String asunto = this.tAsunto.getText();
        String dref = this.tDocs.getText();
        Usuario oUsuario = (Usuario)this.cUsuario.getSelectedItem();
        Dependencia oDependencia = (Dependencia) this.cDependencia.getSelectedItem();
        String inicio = this.tFyH.getText();
        if (id.equalsIgnoreCase("") || prio.equalsIgnoreCase("") || asunto.equalsIgnoreCase("") || dref.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "¡Falta completar datos!");
        }
        else {
            if (esEntero(prio)) {
                int prioridad=Integer.parseInt(prio);
                Expediente oExpediente = new Expediente(id,prioridad,oUsuario,asunto,dref,oDependencia,inicio);
                this.RExpedientes.encolar(oExpediente);
            
                this.tID.setText(null);
                this.tPrioridad.setText(null);
                this.tAsunto.setText(null);
                this.tDocs.setText(null);
                JOptionPane.showMessageDialog(null, "¡Se registró exitosamente!");
            }
            else {
                JOptionPane.showMessageDialog(null, "¡La prioridad asignada debe ser un número entero!");
            }
        }
    }//GEN-LAST:event_BGrabarActionPerformed

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BCerrarActionPerformed

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BGrabar;
    private javax.swing.JComboBox<String> cDependencia;
    private javax.swing.JComboBox<String> cUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tAsunto;
    private javax.swing.JTextField tDocs;
    private javax.swing.JTextField tFyH;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tPrioridad;
    // End of variables declaration//GEN-END:variables
}
